"""Run every decision through every gate and tally what each gate let through.

The output is a receipt, not a report: ``receipts/run.json`` is the canonical
result object and ``receipts/run.md`` is the same figures rendered for reading.
Both are regenerated by ``make receipt``.

The receipt carries no timestamp. It is a function of the committed fixtures and
the committed code and nothing else, so two runs on any machine produce identical
bytes. A timestamp would make the receipt differ from itself for reasons that have
nothing to do with the result.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Callable, Mapping, Sequence

from . import SEED
from .agent import CORRECT, WELL_FORMED_WRONG, Decision, load_decisions
from .domain import Ledger
from .gates import (
    DEFAULT_CONFIDENCE_THRESHOLD,
    GateResult,
    confidence_gate,
    judge_gate,
    reconciliation_gate,
)

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "fixtures"
RECEIPTS = ROOT / "receipts"

Gate = Callable[[Decision, Ledger], GateResult]

GATES: tuple[tuple[str, Gate], ...] = (
    ("confidence_gate", confidence_gate),
    ("judge_gate", judge_gate),
    ("reconciliation_gate", reconciliation_gate),
)

OUTCOMES = ("correct_approvals", "correct_refusals", "dangerous_approvals", "over_refusals")


def classify(decision: Decision, result: GateResult) -> str:
    """Name the confusion-table cell this outcome falls into.

    ``dangerous_approvals`` is the cell that matters: an action the source of truth
    contradicts, approved, on its way to somewhere irreversible.
    """
    if decision.is_wrong:
        return "dangerous_approvals" if result.approved else "correct_refusals"
    return "correct_approvals" if result.approved else "over_refusals"


def compose(decisions: Sequence[Decision]) -> dict:
    kinds: dict[str, int] = {}
    for decision in decisions:
        if decision.is_wrong and decision.wrong_kind is not None:
            kinds[decision.wrong_kind] = kinds.get(decision.wrong_kind, 0) + 1
    return {
        "total": len(decisions),
        "correct": sum(1 for d in decisions if d.is_correct),
        "well_formed_wrong": sum(1 for d in decisions if d.is_wrong),
        "defect_kinds": {kind: kinds[kind] for kind in sorted(kinds)},
    }


def run(world: Ledger, decisions: Sequence[Decision]) -> dict:
    """Run all gates over all decisions and return the canonical result object."""
    gates: dict[str, dict] = {
        name: {
            **{outcome: 0 for outcome in OUTCOMES},
            "dangerous_approvals_by_kind": {},
        }
        for name, _ in GATES
    }
    per_decision = []

    for decision in decisions:
        record = {
            "id": decision.id,
            "label": decision.label,
            "wrong_kind": decision.wrong_kind,
            "gates": {},
        }
        for name, gate in GATES:
            result = gate(decision, world)
            cell = classify(decision, result)
            gates[name][cell] += 1
            if cell == "dangerous_approvals" and decision.wrong_kind is not None:
                by_kind = gates[name]["dangerous_approvals_by_kind"]
                by_kind[decision.wrong_kind] = by_kind.get(decision.wrong_kind, 0) + 1
            record["gates"][name] = {"approved": result.approved, "reason": result.reason}
        per_decision.append(record)

    for name, _ in GATES:
        by_kind = gates[name]["dangerous_approvals_by_kind"]
        gates[name]["dangerous_approvals_by_kind"] = {k: by_kind[k] for k in sorted(by_kind)}

    return {
        "seed": SEED,
        "confidence_threshold": DEFAULT_CONFIDENCE_THRESHOLD,
        "composition": compose(decisions),
        "gates": gates,
        "decisions": per_decision,
    }


def render_markdown(result: Mapping) -> str:
    composition = result["composition"]
    gates = result["gates"]
    kinds = sorted(composition["defect_kinds"])
    lines: list[str] = []

    lines.append("# Receipt")
    lines.append("")
    lines.append(
        f"Seed `{result['seed']}`. Confidence threshold `{result['confidence_threshold']:.2f}`. "
        "No model, no network, no GPU."
    )
    lines.append("")
    lines.append(
        "Regenerate with `make receipt`; re-derive every figure below with `make verify`. "
        "This file carries no timestamp — it is a function of the committed fixtures and the "
        "committed code, so two runs produce identical bytes."
    )
    lines.append("")

    lines.append("## Fixture composition")
    lines.append("")
    lines.append("| | count |")
    lines.append("|---|---|")
    lines.append(f"| decisions | {composition['total']} |")
    lines.append(f"| correct | {composition['correct']} |")
    lines.append(f"| well-formed-wrong | {composition['well_formed_wrong']} |")
    for kind in kinds:
        lines.append(f"| — `{kind}` | {composition['defect_kinds'][kind]} |")
    lines.append("")

    lines.append("## Dangerous approvals")
    lines.append("")
    lines.append(
        "A dangerous approval is a well-formed-wrong decision that the gate approved: "
        "an action the source of truth contradicts, cleared to proceed."
    )
    lines.append("")
    lines.append("| gate | dangerous approvals | of well-formed-wrong |")
    lines.append("|---|---|---|")
    for name, _ in GATES:
        lines.append(
            f"| `{name}` | {gates[name]['dangerous_approvals']} | {composition['well_formed_wrong']} |"
        )
    lines.append("")

    lines.append("## Confusion tables")
    lines.append("")
    lines.append("| gate | correct approvals | correct refusals | dangerous approvals | over-refusals |")
    lines.append("|---|---|---|---|---|")
    for name, _ in GATES:
        row = gates[name]
        lines.append(
            f"| `{name}` | {row['correct_approvals']} | {row['correct_refusals']} | "
            f"{row['dangerous_approvals']} | {row['over_refusals']} |"
        )
    lines.append("")

    lines.append("## Dangerous approvals by defect kind")
    lines.append("")
    header = "| gate | " + " | ".join(f"`{kind}`" for kind in kinds) + " |"
    lines.append(header)
    lines.append("|---|" + "---|" * len(kinds))
    for name, _ in GATES:
        by_kind = gates[name]["dangerous_approvals_by_kind"]
        cells = " | ".join(str(by_kind.get(kind, 0)) for kind in kinds)
        lines.append(f"| `{name}` | {cells} |")
    lines.append("")

    lines.append("Precision is the authority.")
    lines.append("")
    return "\n".join(lines)


def write_receipt(result: Mapping) -> None:
    RECEIPTS.mkdir(exist_ok=True)
    with open(RECEIPTS / "run.json", "w", encoding="utf-8") as handle:
        json.dump(result, handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    with open(RECEIPTS / "run.md", "w", encoding="utf-8") as handle:
        handle.write(render_markdown(result))


def load_world_and_decisions() -> tuple[Ledger, list[Decision]]:
    world = Ledger.load(FIXTURES / "source_of_truth.json")
    decisions = load_decisions(FIXTURES / "decisions.json")
    return world, decisions


def main() -> int:
    world, decisions = load_world_and_decisions()
    result = run(world, decisions)
    write_receipt(result)

    print(f"ran {result['composition']['total']} decisions through {len(GATES)} gates")
    for name, _ in GATES:
        print(f"  {name}: {result['gates'][name]['dangerous_approvals']} dangerous approvals")
    print(f"wrote {RECEIPTS / 'run.json'} and {RECEIPTS / 'run.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
